services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pagemachine\FileVariants\:
    resource: '../Classes/*'
    exclude: '../Classes/Updates/*'

  T3G\AgencyPack\FileVariants\Updates\:
    resource: '../Classes/Updates/*'

  Pagemachine\FileVariants\EventListener\BeforeFileDeletedEventListener:
    tags:
      - name: event.listener
        identifier: file-variants-before-file-delete
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileDeletedEvent

  Pagemachine\FileVariants\EventListener\AfterFileDeletedEventListener:
    tags:
      - name: event.listener
        identifier: file-variants-after-file-delete
        event: TYPO3\CMS\Core\Resource\Event\AfterFileDeletedEvent
